### ISSUE TITLE
Why not use floki as a DSL for scraping page content ?

### ISSUE THREAD

**Issue by merongivian** [fredwu/crawler#1]
Would u consider using it? i can contribute with this

**Comment by sensiblearts** [comment]
Floki is in the dependencies -- is being used by the Parser.

I am guessing that, by "DSL for scraping page content," Fred means a DSL at a higher level than Floki; e.g., what to aggregate, or save.

**Comment by fredwu** [comment]
Hi @merongivian,

@sensiblearts is right - Floki is being used by the parser at the moment. Once I'm ready to implement the scraping feature I will think about how to utilise Floki a bit more, in the form of a higher level DSL or API.

Hope that makes sense. :)

**Comment by merongivian** [comment]
@fredwu got it, just read the codebase so its clear now :)
