### ISSUE TITLE
Links with space are not url encoded and return 404

### ISSUE THREAD

**Issue by julienmarie** [fredwu/crawler#12]
Example:
```
"https://www.city-discovery.com/continent/North America" => 404
"https://www.city-discovery.com/continent/North%20America" => 200
```

**Comment by JPYamamoto** [comment]
@julienmarie Problem solved. You can now call `Crawler.crawl("https://www.city-discovery.com/continent/North America", encode_uri: true)` to have your URL encoded.
I think this issue can be closed.

**Comment by fredwu** [comment]
👏 Thanks @JPYamamoto

**Comment by julienmarie** [comment]
Awesome!
