### ISSUE TITLE
Is there a view to determine webfonts used? 

### ISSUE THREAD

**Issue by untoldbyte** [fredwu/crawler#19]
Just like css, images, JavaScript can we get all webfonts used on a webpage?

**Comment by fredwu** [comment]
Hi, I haven't personally tested it, but the default CSS Parser does parse any `url` elements including web fonts: https://github.com/fredwu/crawler/blob/fedd5a0c27b345d1db5061304c9b7fdcdfea887c/lib/crawler/parser/css_parser.ex
