### ISSUE TITLE
plug_cowboy dependency

### ISSUE THREAD

**Issue by phereford** [fredwu/crawler#22]
Hi @fredwu .

Thank you so much for this awesome (and popular) library! One quick question:
- Is the `plug_cowboy` dependency used in the library outside of testing?

I can't quite find it being used in the library. If not, would you be ok for me to create a PR moving that dependency to the `:test` environment only?

**Comment by fredwu** [comment]
Hi @phereford, to be honest I don't really remember, if you could test it out in non-test envs to make sure it doesn't break anything that'd be awesome! ❤️

**Comment by Awlexus** [comment]
Would it be possible to also update the dependency to version 2? It is causing some conflicts in phoenix 1.4 umbrella projects

**Comment by phereford** [comment]
@awlexus sure! Sorry for the delay here.

**Comment by fredwu** [comment]
Closing thanks to @phereford's PR.

Although, I've tried to update `plug_cowboy` to v2 but it breaks the test suite and I couldn't figure out why from a few glances.
