### ISSUE TITLE
could not compile dependency :crawler

### ISSUE THREAD

**Issue by diegosouza** [fredwu/crawler#31]
Hello people,

I've created a simple project (with and without the `--sup`), I've added `{:crawler, "~> 1.1"}` to my `mix.exs` and then `mix deps.get`. Everything was fine. But when I launch it with: `iex -S mix` I get:

```
# details above omitted

==> crawler
Compiling 32 files (.ex)

== Compilation error in file lib/crawler/fetcher/retrier.ex ==
** (CompileError) lib/crawler/fetcher/retrier.ex:25: undefined function exp_backoff/0
    (elixir 1.10.1) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :crawler, "mix compile" failed. You can recompile this dependency with "mix deps.compile crawler", update it with "mix deps.update crawler" or clean it with "mix deps.clean crawler"
```

Environment info:

- `Linux x30 5.6.10-3-MANJARO #1 SMP PREEMPT Sun May 3 11:03:28 UTC 2020 x86_64 GNU/Linux`
- `Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]`
- `Elixir 1.10.1 (compiled with Erlang/OTP 22)`

Any idea about what's happening? Thanks in advance.

**Comment by kokolegorille** [comment]
It seems to be fixed in master, as the 1.1 uses exp_backoff(), but it should be exponential_backoff().

**Comment by diegosouza** [comment]
@kokolegorille you're right. It's broken.
I hope @fredwu or another core dev release the `1.1.1` release soon.

Thank you all.

**Comment by fredwu** [comment]
Version `1.1.1` released. :)

**Comment by diegosouza** [comment]
Thank you very much!
